app = "speech-processing-api-chwkslwr"
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  min_machines_running = 1

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

app = "speech-processing-api-chwkslwr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  HOST = "0.0.0.0"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = 1
  command = "uvicorn app.main:app --host 0.0.0.0 --port 8000"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = 1

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[deploy]
  strategy = "immediate"
  max_unavailable = 0
