app = "speech-processing-api-chwkslwr"
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"
  release_command = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]
  
  [services.http_checks]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    tls_skip_verify = false

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
