app = "speech-processing-api-chwkslwr"
primary_region = "hkg"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  path = "/"
  timeout = "5s"

[deploy]
  strategy = "immediate"

[processes]
  app = "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"
